#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "findmydevice"
name = "Find My Device"
description.en = "Server for saving location data send by FMD"
description.fr = "Serveur de sauvegarde des données de localisation envoyées par FMD"

version = "0.10.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0-or-later"
code = "https://gitlab.com/Nulide/findmydeviceserver"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://gitlab.com/Nulide/findmydeviceserver/-/archive/v0.10.0/findmydeviceserver-v0.10.0.tar.gz"
        sha256 = "77f3030c430d82d19b9bfaf7d07b493c0e3625b99d5c7dd0d9fcc99a19dca3bc"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
