#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "findmydevice"
name = "Find My Device"
description.en = "Server for saving location data send by FindMyDevice"
description.fr = "Server for saving location data send by FindMyDevice"

version = "0.6.0~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "GPLv3-or-later"
code = "https://gitlab.com/Nulide/findmydeviceserver"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = true
        url = "https://gitlab.com/Nulide/findmydeviceserver/uploads/038f5e2075fc74c14d7b3d8db7b6eaa9/Linux.zip"
        sha256 = "81a28bc53622f4839eb986550f81d6ec436c282fbd631fcd9b54f74b04c864dc"

        [resources.sources.objectbox]
        in_subdir = false
        extract = true
        url = "https://github.com/objectbox/objectbox-c/releases/download/v4.0.1/objectbox-linux-x64.tar.gz"
        sha256 = "ed2003acb1c2d2d6c19bc173d8bb789042a36afabeac333d61a18b1c5712c27a"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
