#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep = "config.yml"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

ynh_go_install

pushd "$install_dir"
	#read -p "Press any key..."
	#ynh_exec_as_app go build ./... -v -o findmydevice
	#ynh_exec_as_app go build -o findmydevice -v
	#ynh_exec_as_app CGO_ENABLED=0 go build -v -ldflags='-s -w' -o $install_dir/
	#export GOPATH="$install_dir"
	#export GOCACHE="$install_dir/.cache"
	#CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/"
	#ynh_exec_as_app make
	#ynh_exec_as_app go run main.go serve
	#ynh_exec_as_app CGO_ENABLED=0 GO111MODULE=on go build -work -v -a -ldflags='-s -w' -o $install_dir/
	#go build -o findmydevice -v
	ynh_exec_as_app go build -o "$install_dir/" main.go
popd

ynh_go_remove

chmod +x "$install_dir/findmydevice"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Server for saving location data send by fmd" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating configuration..."

#ynh_config_add --template="config.example.yml" --destination="$install_dir/config.yml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
